# Generated by Django 4.1.2 on 2022-10-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_user_birthday_user_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
    ]
